#!/usr/bin/env node
// Generates a lightness-keyed tint scale for each key color, borrowing
// Tailwind v4's chroma & hue *curves* (how C and H bend with L) but anchoring
// each scale to our own base hue and peak chroma.
//
// Naming matches the project convention: --color-{name}-{L%}  (e.g. --color-blue-90).

import { readFileSync } from "node:fs";

const tw = JSON.parse(readFileSync(new URL("./tailwind-v4.json", import.meta.url)));

// Our key colors: [L%, C, H]
const BASE = {
	red:     [54, 0.24, 25],
	orange:  [74, 0.19, 58],
	yellow:  [88, 0.2,  95],
	green:   [69, 0.24, 139],
	cyan:    [69, 0.15, 205],
	blue:    [56, 0.24, 260],
	indigo:  [50, 0.27, 275],
	purple:  [57, 0.27, 292],
	magenta: [60, 0.25, 10],
	gray:    [54, 0.04, 250],
};

// Which Tailwind family's curve shape to borrow — pick the one whose base hue
// is closest, so the per-step hue/chroma *deltas* are meaningful. Absolute hue
// is re-anchored to our base anyway, so this only affects curve shape.
const FAMILY = {
	red: "red", orange: "orange", yellow: "yellow", green: "green",
	cyan: "cyan", blue: "blue", indigo: "indigo",
	purple: "violet",   // our purple hue 292 ≈ Tailwind violet
	magenta: "rose",    // our magenta hue 10 ≈ Tailwind rose
	gray: "gray",
};

// Lightness stops (the token number = target L%). Superset of what the codebase uses.
const STOPS = [0, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95];

// Parse "oklch(63.7% 0.237 25.331)" -> [L, C, H]
function parse(str) {
	let [, l, c, h] = str.match(/oklch\(([\d.]+)% ([\d.]+) ([\d.-]+)\)/);
	return [+l, +c, +h];
}

// Per-family curve as points sorted by ascending L.
function curve(family) {
	return Object.values(tw[family]).map(parse).sort((a, b) => a[0] - b[0]);
}

// Linear-interpolate [C, H] at a target lightness along the curve.
// Below/above the data range: chroma fades toward 0 as L→0, hue holds at the end.
function sample(points, L) {
	let lo = points[0], hi = points.at(-1);
	if (L <= lo[0]) {
		return [lo[1] * (L / lo[0]), lo[2]]; // fade chroma toward black
	}
	if (L >= hi[0]) {
		return [hi[1], hi[2]];
	}
	for (let i = 1; i < points.length; i++) {
		let a = points[i - 1], b = points[i];
		if (L <= b[0]) {
			let t = (L - a[0]) / (b[0] - a[0]);
			return [a[1] + t * (b[1] - a[1]), a[2] + t * (b[2] - a[2])];
		}
	}
}

let out = [
	"/*",
	" * Color tints, keyed by lightness (token number = L%).",
	" * Chroma & hue curves borrowed from Tailwind v4, re-anchored to our base palette.",
	" * Generated by files/gen-tints.js — do not edit by hand.",
	" */",
	"",
	":root {",
];

for (let [name, [L0, C0, H0]] of Object.entries(BASE)) {
	let points = curve(FAMILY[name]);
	// Anchor: hue offset and chroma scale evaluated at our base lightness.
	let [cAnchor, hAnchor] = sample(points, L0);
	let hueOffset = H0 - hAnchor;
	let chromaScale = C0 / cAnchor;

	out.push(`\t/* ${name} — base oklch(${L0}% ${C0} ${H0}) */`);
	for (let stop of STOPS) {
		let [c, h] = sample(points, stop);
		c = c * chromaScale;
		h = h + hueOffset;
		// normalize hue to [0, 360)
		h = ((h % 360) + 360) % 360;
		out.push(`\t--color-${name}-${stop}: oklch(${stop}% ${c.toFixed(3)} ${h.toFixed(1)});`);
	}
	out.push("");
}

out.push("}");
process.stdout.write(out.join("\n") + "\n");
